# Generated by Django 4.1.2 on 2022-10-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiveYearPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=3)),
                ('grid_demand_forecast', models.IntegerField()),
                ('required_power_reserve', models.IntegerField()),
                ('surplus_capacity', models.IntegerField()),
                ('available_capacity', models.IntegerField()),
                ('available_capacity_for_tso', models.IntegerField()),
                ('cent_dispatched_units_gen_forecast', models.IntegerField()),
                ('non_cent_dispatched_units_gen_forecast', models.IntegerField()),
                ('wind_gen_forecast', models.IntegerField()),
                ('pv_gen_forecast', models.IntegerField()),
                ('planned_cross_border_exchange', models.IntegerField()),
                ('network_losses_forecast', models.IntegerField()),
                ('capacity_market_obligation', models.IntegerField()),
            ],
        ),
    ]
